sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
install: pip install colony
env:
  global:
    - REPO_URL_OMNI="https://colony.bemisc.com/"
    - REPO_USERNAME=root
    - secure: iQ5ZqP3LRClPzhVInaGqDJW0mQ/vjDylKVSxYEwoyw1F6o4WPGEhmOxEmdBT1L6YJ3mKhg45PBUKaBrQTeXTsJytWCP9gD8pFDUVaD9Lr3CQvag5sG9R5fLHVwme/AABUscgvLh8rUP6bMXgXZH2US4njszXfdR7wmOvM5PCh+o=
script: echo ""
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then cpm upload "./*" colony; fi
