dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install: pip install colony
env:
  global:
    - REPO_URL_OMNI="https://colony.bemisc.com/"
    - REPO_USERNAME=root
    - secure: iQ5ZqP3LRClPzhVInaGqDJW0mQ/vjDylKVSxYEwoyw1F6o4WPGEhmOxEmdBT1L6YJ3mKhg45PBUKaBrQTeXTsJytWCP9gD8pFDUVaD9Lr3CQvag5sG9R5fLHVwme/AABUscgvLh8rUP6bMXgXZH2US4njszXfdR7wmOvM5PCh+o=
script: echo ""
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then cpm upload "./*" colony; fi
